### ISSUE TITLE
I found newer "grid.c" (ported from 0.9 branch?)

### ISSUE THREAD

**Issue by SLiTaz-Linux** [compiz-reloaded/compiz-plugins-extra#1]
Looks like unfinished job to port grid-0.9 features to 0.8.
24k grid.c vs 8k in this repo.
Who knows, maybe it was missed by compiz-reloaded developers.
On this page http://forums.mate-desktop.org/viewtopic.php?f=16&t=3175&start=10
File "grid.zip"
http://forums.mate-desktop.org/download/file.php?id=399

plugins-extra compiles when overwriting grid.c, but results in "undefined symbol" error on start.

Please review, is it possible to fix this?

**Comment by XRevan86** [comment]
> maybe it was missed by compiz-reloaded developers

It was :-).
