### ISSUE TITLE
Feature request: drag-to-edge for grid plugin

### ISSUE THREAD

**Issue by Pival81** [compiz-reloaded/compiz-plugins-extra#11]
Hi, I recently learned that this functionality is only available on Compiz 0.9, and that 0.9 is only made for Unity, and won't work well with other DEs.
Now, i can't use 0.9 because it's too buggy, but neither 0.8 because of this missing functionality, and i REALLY don't want to use xfwm4 because it lacks the expo feature.
Can it be included in compiz-reloaded?

**Comment by ethus3h** [comment]
This is already implemented ("Resize Actions" in "Corners/Edges" tab). Do you have the latest compiz-reloaded installed?

**Comment by Pival81** [comment]
@ethus3h where? i don't see it anywhere.

**Comment by ethus3h** [comment]
Compiz, or Compiz-Reloaded?

I only see Compiz listed in software.opensuse.org, and that package isn't supported here I don't think.

**Comment by Pival81** [comment]
@ethus3h i'm using the packages in [this repo](https://build.opensuse.org/project/show/X11:Compiz), and as you can see from the spec files, they are directly from compiz-reloaded.

**Comment by ethus3h** [comment]
Huh, I dunno then, sorry ¯\\\_(ツ)_/¯

**Comment by soreau** [comment]
You probably want to talk to XRevan86 and/or use https://build.opensuse.org/project/show/X11:Compiz

**Comment by Pival81** [comment]
@soreau but i'm using exactly that repo!

**Comment by soreau** [comment]
@Pival81 The functionality you seek was [recently committed in 0b2a65](https://github.com/compiz-reloaded/compiz-plugins-extra/commit/0b2a6524c987c5615b9be5223c48bd99d3d13a33). If you have this commit, grid will have the "Corners / Edges" tab.

**Comment by Pival81** [comment]
@soreau thank you! i think tomorrow i will make a repo to have the latest commits from compiz-reloaded on opensuse, and update it weeky.
