### ISSUE TITLE
Wallpaper plugin _NET_WM_WINDOW_TYPE_DESKTOP property causes Nemo to skip desktop setup

### ISSUE THREAD

**Issue by Tank-Missile** [compiz-reloaded/compiz-plugins-extra#16]
Getting Nemo File Manager and Compiz Wallpaper plugin to work nicely together has been a bit of a hassle. It works, but only if Nemo is started first since it skips managing the desktop if any other _NET_WM_WINDOW_TYPE_DESKTOP properties are detected. This can be bypassed by supplying the WM_CLASS of the wallpaper to org.nemo.desktop.ignored-desktop-handlers, but the plugin does not appear to have one.

**Comment by soreau** [comment]
@Tank-Missile Does [this patch](http://sprunge.us/eLOD) help? It sets the window class string to "Compiz-Wallpaper". Apply to _compiz-plugins-extra_ with `git apply /path/to/patch.diff`
