### ISSUE TITLE
Grid doesn't work properly when using 2 monitors

### ISSUE THREAD

**Issue by bitstrings** [compiz-reloaded/compiz-plugins-extra#19]
Got 2 - 4K monitors, 1 is rotated 90deg left.

When touching sides most times the window is tiled on the other monitor.

**Comment by bitstrings** [comment]
In fact the behavior seems to be that if enough of the window is dragged off the edge the snapping occur on the other screen.

**Comment by bitstrings** [comment]
Also, grid doesn't seem to play nice with a multi-monitor setup. Looks like it sees 1 huge screen.

**Comment by soreau** [comment]
It would be nice to have an idea of what is supposed to happen in these cases. I'm guessing you're wanting to be able to grid on the edges of the monitors where they 'touch'? How would that behave since there's no edge where the mouse stops between monitors?

**Comment by bitstrings** [comment]
Well, the grid plugin from Ubuntu compiz (launchpad) works as expected.

Touching any of the monitors edge will tile the window as expected.

Compiz reloaded is compatible with a multi-monitor setup since other plugins use the information to provide the correct experience. I guess grid doesn't?

**Comment by soreau** [comment]
Yes, it's just a matter of coding. In the 0.9 version do you have to approach the edge slowly to be careful not to accidentally go into the other monitor and grid the the other monitor? I'm thinking we could make it so across the 'middle edge' between monitors could grid on the monitor where the grab initiated and don't 'activate' the grid area near the edge of the other monitor, unless moving into a 'hard edge' of the other monitor. Does that make any sense?

**Comment by bitstrings** [comment]
Depending on how much window "gets out" from the screen then the tiling occurs on the other monitor.

For example, if I grab the window on top left corner and drag it on the left then it tiles on the correct screen. I grab the window on top right corner and drag it on the left then it tiles on the other screen.

**Comment by soreau** [comment]
It sounds like perhaps they're using the middle point of the window as the determining factor.

For the rotated 90 degrees problem, is it the same as what we're talking about now, or is it a different problem?

**Comment by bitstrings** [comment]
Yeah, I just mentioned my setup, I think fixing the dragging problem should resolve the issue.

**Comment by soreau** [comment]
Noted. Thanks for the report, it will be closed when resolved upstream.
