### ISSUE TITLE
Bug: Grid: When tearing off from grid positions other than maximised, the window should return to its previous size.

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz-plugins-extra#2]
Bug: Grid: When tearing off from grid positions other than maximised, the window should return to its previous size. (This works as expected when unmaximising windows.)

**Comment by soreau** [comment]
Fixed with [478453a](https://github.com/compiz-reloaded/compiz/commit/478453a1da044c64813c6f859c33c15a3252994b)

**Comment by ethus3h** [comment]
Awesome, thanks! :D
