### ISSUE TITLE
transformed windows appear discolored when using alpha blur

### ISSUE THREAD

**Issue by psykotik1** [compiz-reloaded/compiz-plugins-extra#22]
![screenshot_20171211_223820](https://user-images.githubusercontent.com/11342059/33867871-0a7c29d6-dec5-11e7-8d71-f36fd804c74b.png)

using open source ati driver

**Comment by psykotik1** [comment]
solved using this command: R600_DEBUG=sbsafemath compiz --replace & disown

**Comment by soreau** [comment]
Can you say what type of blur filter this happens with? Or does it happen with all? (4x Bilinear, Gaussian, Mipmap) It might be worth reporting a bug at bugs.freedesktop.org for the r600 driver.
